name: cert-lgs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pyyaml
  - networkx
  - scikit-learn
  - tqdm
  - pytest
  - pip:
      - pytest-cov
      - ruff
      - mypy
      - -e .[dev]
